# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: $(Date:yyyyMMdd)$(Rev:.r).0-$(SourceBranchName)

parameters:
- name: SignTypeOverride
  displayName: Signing type override
  type: string
  default: default
  values:
  - default
  - test
  - real

schedules:
- cron: 0 6 * * 0
  branches:
    include:
    - main
  always: "true"

pr:
  - main

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

variables:
  ${{ if ne(parameters.SignTypeOverride, 'default') }}:
    SignType: ${{ parameters.SignTypeOverride }}
  ${{ if and(eq(parameters.SignTypeOverride, 'default'), or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), eq(variables['Build.SourceBranchName'], 'main'))) }}:
    SignType: real
  ${{ if and(eq(parameters.SignTypeOverride, 'default'), not(or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), eq(variables['Build.SourceBranchName'], 'main')))) }}:
    SignType: test

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
      tsa:
        enabled: true
        GdnPublishTsaOnboard: true
        GdnPublishTsaConfigFile: $(Build.SourcesDirectory)\build\tsa.gdntsa
      policheck:
        enabled: true
      spotBugs:
        enabled: false # Turn this off, this isn't java.
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - template: /build/build.yml@self
